import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | ToolCorners',
  description: 'Read the terms of service for ToolCorners. Simple, clear, and focused on providing a high-quality user experience.',
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in duration-700">
      <div className="text-center space-y-4">
        <h1 className="text-5xl font-black tracking-tighter">
          <span className="gradient-text">Terms of Service</span>
        </h1>
        <p className="text-slate-600 dark:text-slate-400 text-lg font-medium">
          Straightforward rules for a straightforward tool.
        </p>
      </div>

      <section className="glass-morphism p-8 md:p-12 space-y-8">
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-50">1. Acceptance of Terms</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            By using ToolCorners, you agree to these terms. Our tools are provided "as is" for your convenience and productivity.
          </p>
        </div>

        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-50">2. Permitted Use</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            You are free to use these tools for personal or commercial projects. We do not place any restrictions on the number of conversions you perform or the volume of data you process.
          </p>
        </div>

        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-50">3. No Liability</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            While we strive for 100% accuracy, ToolCorners is not liable for any errors in conversion or data loss. Since all processing happens in your browser, you are responsible for the data you input and the files you download.
          </p>
        </div>

        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-50">4. Intellectual Property</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            The ToolCorners interface and custom logic are protected. However, the output generated by our tools (your converted files) belongs entirely to you.
          </p>
        </div>

        <div className="pt-8 border-t border-slate-200 dark:border-slate-800">
          <p className="text-xs text-slate-500 font-medium italic">
            Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>
      </section>
    </div>
  );
}
